Class {
	#name : #PenEventSymbol,
	#superclass : #Object,
	#category : #'Penfeld-Events'
}

{ #category : #symbols }
PenEventSymbol class >> action [
	^ #action
]

{ #category : #symbols }
PenEventSymbol class >> click [
	^ #click
]

{ #category : #symbols }
PenEventSymbol class >> mouseDown [
	^ #mouseDown
]

{ #category : #symbols }
PenEventSymbol class >> mouseEnter [
	^ #mouseEnter
]

{ #category : #symbols }
PenEventSymbol class >> mouseHover [
	^ #mouseHover
]

{ #category : #symbols }
PenEventSymbol class >> mouseUp [
	^ #mouseUp
]

{ #category : #symbols }
PenEventSymbol class >> resize [
	^ #resize
]

{ #category : #symbols }
PenEventSymbol class >> selectionChanged [
	^ #selectionChanged
]

{ #category : #symbols }
PenEventSymbol class >> valueChanged [
	^ #valueChanged
]
